### ISSUE TITLE
Feauture request: Custom Markers (styling part) and some other stuff

### ISSUE THREAD

**Issue by phrizm** [morehawes/Waymark#23]
Ok here we go with feauture requests:

- Ability to add a custom marker without background (even if i add a custom font awesome icon it's still has background shape).
- Ability to add a svg as custom marker (custom one svg) (maybe drag and drop).

Maps proveders free tiles list (please link a list of free tile's providers in order to simplify a option selection).

Elevation styles (those default looks kinda cartoonish, its way better to implement something like https://github.com/GIScience/Leaflet.Heightgraph/blob/master/README.md) - looks badass :)

Implement https://github.com/Leaflet/Leaflet.markercluster
In order to group several markers.

So here is a lot of things going on, but! Who knows maybe once those gonna be implemented :) thank you!

**Comment by morehawes** [comment]
Thanks for the input @phrizm, greatly appreciated.

>     * Ability to add a custom marker without background (even if i add a custom font awesome icon it's still has background shape).

You can hide the background with CSS, I put together an [example](https://www.waymark.dev/docs/marker-without-background/). Let me know if this is not what you meant, the markers are HTML/CSS so pretty customisable.

>     * Ability to add a svg as custom marker (custom one svg) (maybe drag and drop).

I'm not exactly sure what you mean here, especially the drag and drop part. You can add a SVG image to a Marker with a HTML icon like `<img src="http://link.to/icon.svg" />`.

> Maps proveders free tiles list (please link a list of free tile's providers in order to simplify a option selection).

Good point, I will add [this list](https://leaflet-extras.github.io/leaflet-providers/preview/) to the plugin Settings > Basemaps page.
 
> Elevation styles (those default looks kinda cartoonish, its way better to implement something like https://github.com/GIScience/Leaflet.Heightgraph/blob/master/README.md) - looks badass :)

That does look good and it's based on [Leaflet.Elevation](https://github.com/MrMufflon/Leaflet.Elevation) which Waymark uses, so that's a plus. However Waymark and Leaflet.Elevation are pretty interwoven with lots of weird fixes so it's going to be alot of work to re-do.

I'm definitely on board for improving the Elevation feature in the long term though.

> Implement https://github.com/Leaflet/Leaflet.markercluster In order to group several markers.

It's on my to-do list and I have already started work on this :)

Thanks again,

Joe

**Comment by phrizm** [comment]
Thank you!

Now I will stop annoying you!

I perfectly know that we can't satisfy every one's needs, but some margin to improvement is always there (reasonable common usage).

I'm on hard work for my cpt gallery plugin that actually kicks ass pretty hard. Using swiper and masonry for layouting.

I hope your majesty once take a look when it's in a pretty good finished state and maybe we can integrate maps features in order to work with maps also like Metadata and so on (idk) . Ofc it's open source. 

So said that: first raw preview is here:

https://drive.google.com/file/d/1A8FcifADxQRaFJAsa7yuiSWptz0f8jwE/view?usp=drivesdk

Off closing this issue ( maybe you can create a discussion section).

Cheers!
